# Generated by Django 5.1.6 on 2025-03-02 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num', models.IntegerField(blank=True, null=True)),
                ('crn', models.CharField(max_length=10)),
                ('subject', models.CharField(max_length=10)),
                ('course', models.CharField(max_length=10)),
                ('section', models.CharField(max_length=10)),
                ('title', models.CharField(max_length=255)),
                ('instructor', models.CharField(max_length=255)),
                ('dates', models.CharField(max_length=255)),
                ('seats', models.CharField(max_length=50)),
                ('waitlist', models.CharField(max_length=50)),
            ],
        ),
    ]
