# Generated by Django 5.1.6 on 2025-03-03 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='course',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='course',
            name='crn',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='course',
            name='section',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='course',
            name='subject',
            field=models.CharField(max_length=20),
        ),
    ]
