# Generated by Django 5.1.6 on 2025-04-23 17:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_remove_course_dates_course_final_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='num',
        ),
    ]
